#!/bin/bash
# Switch and rebase on top of upstream
set -e

branch="${1}"

if [ -z "${branch}" ]
then
    branch="$(git branch --show-current)"
fi

if [ -z "$(git branch | cat | grep -w $branch)" ]
then
    echo "${branch} does not exist locally, checking out..."
    git fetch upstream
    git checkout --track upstream/$branch
    git branch --set-upstream-to origin
else
    git switch $branch
    git pull origin $branch
    git fetch upstream
    git rebase upstream/$branch
fi
